#!/usr/bin/env python3
"""
GSC Data Fetcher (CI version)
Fetches Google Search Console search analytics for aitoolcrux.com.
Uses service account JSON from GOOGLE_SERVICE_ACCOUNT_JSON env var.
Outputs report to gsc-ga4-report/ directory.
"""
import json
import os
import sys
from datetime import datetime, timedelta, timezone

SITE_URL = "https://www.aitoolcrux.com/"
SCOPES = ["https://www.googleapis.com/auth/webmasters.readonly"]
OUTPUT_DIR = os.path.join(os.environ.get("GITHUB_WORKSPACE", "."), "gsc-ga4-report")


def get_service():
    cred_json = os.environ.get("GOOGLE_SERVICE_ACCOUNT_JSON")
    if not cred_json:
        print("ERROR: GOOGLE_SERVICE_ACCOUNT_JSON env var not set")
        sys.exit(1)

    from google.oauth2 import service_account
    from googleapiclient.discovery import build

    cred_data = json.loads(cred_json)
    credentials = service_account.Credentials.from_service_account_info(
        cred_data, scopes=SCOPES
    )
    return build("searchconsole", "v1", credentials=credentials, cache_discovery=False)


def query(service, dimensions=None, row_limit=50, start_date=None, end_date=None):
    if not end_date:
        end_date = datetime.now(timezone.utc).date() - timedelta(days=2)
    if not start_date:
        start_date = end_date - timedelta(days=29)

    body = {
        "startDate": start_date.isoformat(),
        "endDate": end_date.isoformat(),
        "dimensions": dimensions or [],
        "rowLimit": row_limit,
    }
    req = service.searchanalytics().query(siteUrl=SITE_URL, body=body)
    return req.execute()


def main():
    print("Fetching GSC data...")
    service = get_service()

    end_date = datetime.now(timezone.utc).date() - timedelta(days=2)
    start_date = end_date - timedelta(days=29)
    prev_end = start_date - timedelta(days=1)
    prev_start = prev_end - timedelta(days=29)

    # Totals
    totals = query(service, start_date=start_date, end_date=end_date)
    rows = totals.get("rows", [])
    clicks = rows[0]["clicks"] if rows else 0
    impressions = rows[0]["impressions"] if rows else 0
    ctr = rows[0]["ctr"] if rows else 0
    position = rows[0]["position"] if rows else 0

    # Previous period
    prev = query(service, start_date=prev_start, end_date=prev_end)
    prev_rows = prev.get("rows", [])
    prev_clicks = prev_rows[0]["clicks"] if prev_rows else 0
    prev_impressions = prev_rows[0]["impressions"] if prev_rows else 0

    # Top pages
    top_pages = query(service, dimensions=["page"], row_limit=20,
                      start_date=start_date, end_date=end_date)

    # Top queries
    top_queries = query(service, dimensions=["query"], row_limit=20,
                        start_date=start_date, end_date=end_date)

    # By device
    by_device = query(service, dimensions=["device"], row_limit=10,
                      start_date=start_date, end_date=end_date)

    # Build report
    report = f"""# GSC Report: aitoolcrux.com

Period: {start_date} to {end_date}
Generated: {datetime.now(timezone.utc).isoformat()}

## Summary

| Metric | This Period | Previous Period | Change |
|--------|------------|-----------------|--------|
| Clicks | {clicks} | {prev_clicks} | {clicks - prev_clicks:+d} |
| Impressions | {impressions} | {prev_impressions} | {impressions - prev_impressions:+d} |
| CTR | {ctr*100:.2f}% | - | - |
| Avg Position | {position:.2f} | - | - |

## Top Pages

| Page | Clicks | Impressions | CTR | Position |
|------|--------|-------------|-----|----------|
"""
    for r in top_pages.get("rows", []):
        page = r["keys"][0].replace("https://www.aitoolcrux.com", "")
        report += f"| {page} | {r['clicks']} | {r['impressions']} | {r['ctr']*100:.1f}% | {r['position']:.1f} |\n"

    report += "\n## Top Queries\n\n| Query | Clicks | Impressions | CTR | Position |\n|-------|--------|-------------|-----|----------|\n"
    for r in top_queries.get("rows", []):
        report += f"| {r['keys'][0]} | {r['clicks']} | {r['impressions']} | {r['ctr']*100:.1f}% | {r['position']:.1f} |\n"

    report += "\n## By Device\n\n| Device | Clicks | Impressions | Avg Position |\n|--------|--------|-------------|---------------|\n"
    for r in by_device.get("rows", []):
        report += f"| {r['keys'][0]} | {r['clicks']} | {r['impressions']} | {r['position']:.2f} |\n"

    report += f"\n---\n*Generated by gsc-fetch workflow*\n"

    os.makedirs(OUTPUT_DIR, exist_ok=True)
    filename = f"{start_date}_{end_date}.md"
    filepath = os.path.join(OUTPUT_DIR, filename)
    with open(filepath, "w", encoding="utf-8") as f:
        f.write(report)

    print(f"Report saved: {filepath}")
    print(f"Clicks: {clicks}, Impressions: {impressions}, CTR: {ctr*100:.2f}%, Pos: {position:.2f}")


if __name__ == "__main__":
    main()
